// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller.js"
application.register("alert", AlertController)

import BudgetController from "./budget_controller.js"
application.register("budget", BudgetController)

import DatatablesController from "./datatables_controller.js"
application.register("datatables", DatatablesController)

import MessageController from "./message_controller.js"
application.register("message", MessageController)

import NewFormController from "./new_form_controller.js"
application.register("new-form", NewFormController)

import Select2Controller from "./select2_controller.js"
application.register("select2", Select2Controller)
